<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ecza_imu</name>
  <version>0.1.0</version>
  <description>GY-85 IMU driver (ADXL345 + ITG3205 + HMC5883L) for ecza-robotu</description>
  <maintainer email="hasan110400@gmail.com">Emre Kabaoğlu</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
